# SPDX-FileCopyrightText: © 2015 Team CharLS
# SPDX-License-Identifier: BSD-3-Clause

version: 3.0.0.{build}
skip_branch_with_pr: true
os: Visual Studio 2019
configuration:
- Debug
- Release
platform:
- x86
- x64
build:
  project: charls.sln
  verbosity: minimal
