# SPDX-FileCopyrightText: © 2015 Team CharLS
# SPDX-License-Identifier: BSD-3-Clause

version: 2.1.1.{build}
os: Visual Studio 2019
configuration:
- Debug
- Release
platform:
- x86
- x64
before_build:
- nuget restore
build:
  project: CharLS.sln
  verbosity: minimal